### ISSUE TITLE
Unsure which version works for which SM release

### ISSUE THREAD

**Issue by MountFranklin** [ca25nada/spawncamping-wallhack#17]
I updated to the master branch of SCWH on SM5.1 but lost song info and song preview on the main menu. I went through previous issues and noticed that the only real doccumented release would be 5.0.12 and SCWH, but in running the same version and the SCWH release for 5.0.12 I've reverted back the menu and some details.

I've deleted and re-installed SM but it's not clear what version of SCWH now works with the latest SM build. I was wondering if you could list which version the current master branch works on what SM build? It says Etterna 0.58+ but the Etterna repo only lists 0.57 so I'm back to SM. I had it previously installed but I updated and removed the old version thinking there was support.

**Comment by ca25nada** [comment]
Currently it's as follows:


- **Master Branch:** Etterna 0.58 or later. 0.58 is currently unreleased so you'll either have to compile it yourself from etterna's `develop` branch or ask the etterna devs for the appveyor builds.

- **SM 5.0's release of 2.0.1:** SM 5.0.12 or later, which is now known as SM 5.1. The theme should still work fine with the current 5.1 release. Otherwise, please let me know so I can fix it up quickly.

- **SM 5.1's release of 2.0.1:** *Strictly SM 5.1.-3 only.* StepMania 5.1 became 5.2 when the SM devs moved up their 5.0 branch to 5.1 (I honestly don't know why). Also, I'm almost certain the changes made for 5.2 are significant enough to break the theme.

**Comment by MountFranklin** [comment]
They are indeed significant enough. The only reason I came here was because I decided I wanted to move up to 5.2 and then update to the latest branch.

Thanks a heap for labelling the branches like that, it makes it super easy to grab the right copy now. I'll pull a copy of 2.0.1 and re-install it to a 5.1.-3 build

**Comment by MountFranklin** [comment]
I've installed and played with a bit, and it is a bit better then what I had, but the song options menu is combined in that version and the previous version I ran had their individual menus. Is this because I originally was running the master branch but you have since updated it only for Etterna?

**Comment by ca25nada** [comment]
Not exactly sure, but I removed the song options screen after moving the commonly used mods (rates, background options) from that screen into player options. That was a while ago though.

**Comment by MountFranklin** [comment]
Lucky enough I had a shadowplay recording.

Old menu I was using: https://i.imgur.com/7anLLxf.png
Current menu: https://i.imgur.com/TPL81bg.jpg

I know it's out of date, but I have a feeling it's like, REALLY out of date.

**Comment by ca25nada** [comment]
I honestly don't remember when the menu system got updated on 5.1 anymore, but as far as theme features go... I don't think it was too out of date from the release version.
