### ISSUE TITLE
Game Stuck

### ISSUE THREAD

**Issue by ETKinji** [ca25nada/spawncamping-wallhack#30]
![Etterna_2020-11-09_19-28-39](https://user-images.githubusercontent.com/74186065/98536406-bd4ef400-22c2-11eb-94b4-cda281f14e78.png)

I've just downloaded the theme and I have no problem load it up but when I select a song to play the game seems to stuck like this with the song playing at the background.

**Comment by kaymick2** [comment]
I have the same issue

**Comment by poco0317** [comment]
The released version is marked for a specific version of Etterna because it is only compatible with that version of Etterna.
If you want to use Etterna 0.70.3 with this theme, download this release temporarily until Etterna 0.71.0 comes out:
https://github.com/poco0317/spawncamping-wallhack/releases/tag/2.2.5a
