### ISSUE TITLE
Song options

### ISSUE THREAD

**Issue by Dissignator** [ca25nada/spawncamping-wallhack#9]
Song options does not show for me. I have changed the setting song options to show and when it didn´t work i reinstalled

**Comment by ca25nada** [comment]
The theme has the screen disabled regardless of preference.

For 5.0 versions the commonly used options in song options (e.g. rates) was moved to player options.

For 5.1 versions the theme uses nesty option screen instead of the old player/song options screen. It should have _most_ (not all, as things like fail preferences are still missing) options that were in the old song options screen.
